sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t test-image -f Dockerfile.dev .

script:
  - docker run -e CI=true test-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-ap-southeast-2-772022640202
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
